### ISSUE TITLE
Question: How to adjust timer for ping status scans?

### ISSUE THREAD

**Issue by aaronSkar** [pierrecdn/phpipam-agent#1]
The README.md page says scans will be completed by default every 15 minutes.  When looking within the docker conainter I do not see a 15 minute interval in the cron jobs.  I am also not sure why there are 2 cronjobs that appear to do the same thing?  

Any help in understand how to set a custom timer for the agent scan is appreciated!  Thanks for putting this docker image together btw!

```
root@eafb172b005c:/opt/phpipam-agent# cat /etc/cron.d/phpipam 
* * * * * /usr/local/bin/php /opt/phpipam-agent/index.php update > /proc/1/fd/1 2>/proc/1/fd/2

root@eafb172b005c:/opt/phpipam-agent# cat /var/spool/cron/crontabs/root 
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/etc/cron.d/phpipam installed on Thu Sep  6 23:59:09 2018)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
* * * * * /usr/local/bin/php /opt/phpipam-agent/index.php update > /proc/1/fd/1 2>/proc/1/fd/2
```

**Comment by pierrecdn** [comment]
Hi,

In fact the crontab definition, which is originally in /etc/cron.d/phpipam is copied into /var/spool/cron/crontabs/root. You can check how this container is built you'll see that there's only one source of truth for this crontab.

Also, the frequency is every 1mn here.
I was sure that no-one would agree on an arbitrary delay, so I chose to set it to the lowest possible interval.

To check that everything is OK, I encourage you to run it and check what happen by doing
`docker logs -f ipam-agent`

**Comment by aaronSkar** [comment]
Perfect, thanks!
