### ISSUE TITLE
Timestamp on scan agent

### ISSUE THREAD

**Issue by blaz15** [pierrecdn/phpipam-agent#2]
Hello,

The timestamp that shows in my phpipam instance for when the phpipam-agent docker was last accessed is 6 hours ahead of my real time. I have already synced my host's time with the phpipam application docker container and the phpipam-agent docker container via my docker-compose file. When I run my cron job, the timestamp is 6 hours ahead of what is actually the time where I am. Where is this being set or pulled from?

Here are some screenshots to show you what I mean. The first shows that the last scan was at 21:43. The second shows that I had the cronjob set to run at 15:43 (6 hour difference). The third shows that both of my containers are in sync with the time of the machine hosting the phpipam instance.

![screenshot from 2019-01-23 16-21-09](https://user-images.githubusercontent.com/46978628/51641381-9bd51a80-1f2b-11e9-9057-70afdfdb1b27.png)
![screenshot from 2019-01-23 16-23-21](https://user-images.githubusercontent.com/46978628/51641394-a2639200-1f2b-11e9-95fd-8186958b2b29.png)
![screenshot from 2019-01-23 16-24-59](https://user-images.githubusercontent.com/46978628/51641396-a4c5ec00-1f2b-11e9-8e14-0f7f10b6495a.png)

**Comment by pierrecdn** [comment]
Hi,
What is your timezone?

**Comment by blaz15** [comment]
Hi,
America/Chicago

**Comment by pierrecdn** [comment]
I would first say that:
* on one side you have the system time (and cron jobs logs etc.) 
* on another you have the javascript using your local TZ.

I guess the 6 hours offset in fact comes from the offset you have with UTC.

IMO the problem would be the same on a bare metal phpipam install on a server setup with a different TZ than the one of the end user.

So it's probably worth opening an issue on the phpipam/phpipam project itself.

**Comment by blaz15** [comment]
Hello,
Sorry for the delayed response to your answer. I appreciate it btw. The issue with the timezone being different than my own comes from the php.ini file in the phpipam docker image and the phpipam-agent docker image. There is a setting in both files that set the timezone to UTC. This issue can be closed, thanks again!
